use_frameworks!

target 'UNDSNumberPadHelper_Example' do
  pod 'UNDSNumberPadHelper', :path => '../'
  pod 'UNDanielBasicTool_Swift', :path => '~/Developer/Libraries/UNDaniel Basic Tool for Swift'

  target 'UNDSNumberPadHelper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
